export const colors = {
  black: 'var(--black)',
  white: 'var(--white)',
  grey6: 'var(--dark)',
  grey5: 'var(--grey)',
  grey4: 'var(--border)',
  grey3: 'var(--darkened)',
  grey2: 'var(--light)',
  grey1: 'var(--background)',
  grey0: 'var(--grey-accent)',
  blue: 'var(--blue)',
  blue3: 'var(--blue-light)',
  blue2: 'var(--blue-very-light)',
  blue1: 'var(--blue-extra-light)',
  blueGreen: 'var(--blue-green)',
  blueGreen1: 'var(--green-dark)',
  blueGreen2: 'var(--green-high-contrast)',
  green: 'var(--green)',
  green1: 'var(--green-light)',
  reassigned: 'var(--reassigned)',
  danger: 'var(--danger)',
  secondary: 'var(--secondary)',
  purple: 'var(--purple)',
  highlight: 'var(--highlight)',
  closedResolved: 'var(--closedResolved)',
  primary: 'var(--blue)',
}
